AUGMENTATION: True
IMAGE_HEIGHT: 320 
IMAGE_WIDTH: 416
BATCH_SIZE: 32
INCLUDE_TOP: False
EPOCHS: 100
NUM_CLASSES: 20
WEIGHTS: imagenet
LEARNING_RATE: 0.0001
CLASSES: [
        "Background",
        "Hat",
        "Hair",
        "Glove",
        "Sunglasses",
        "UpperClothes",
        "Dress",
        "Coat",
        "Socks",
        "Pants",
        "Torso-skin",
        "Scarf",
        "Skirt",
        "Face",
        "Left-arm",
        "Right-arm",
        "Left-leg",
        "Right-leg",
        "Left-shoe",
        "Right-shoe"
    ]
