artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/tentotheminus9/seti-data
  data_dir: artifacts/data_ingestion

model_building:
  root_dir: artifacts/model_building
  updated_base_model_path: artifacts/model_building/base_model_updated.keras